const voiceConfig = {
  intents: [
    { action: 'on', patterns: ['turn on', 'switch on', 'enable', 'activate', 'start', 'power on'] },
    { action: 'off', patterns: ['turn off', 'switch off', 'disable', 'deactivate', 'stop', 'power off', 'shut down'] },
    { action: 'open', patterns: ['open', 'unlock'] },
    { action: 'close', patterns: ['close', 'lock', 'shut'] },
    { action: 'set', patterns: ['set', 'increase', 'decrease', 'change', 'adjust'] },
    { action: 'temperature', patterns: ['set temperature', 'change temperature', 'adjust temperature', 'temperature to', 'temp to', 'cool to', 'warm to', 'heat to'] },
    { action: 'brightness', patterns: ['dim', 'brighten', 'set brightness', 'change brightness', 'brightness to', 'dim to', 'brightness level'] },
    { action: 'speed', patterns: ['set speed', 'change speed', 'speed to', 'increase speed', 'decrease speed', 'fan speed', 'speed level'] },
    { action: 'mode', patterns: ['set mode', 'change mode', 'mode to', 'switch to', 'enable mode', 'activate mode'] },
    { action: 'scene', patterns: ['goodnight', 'good night', 'movie mode', 'movie time', 'party mode', 'party time', 'dinner mode', 'reading mode', 'away mode', 'sleep mode', 'wake up', 'morning mode', 'relax mode', 'eco mode', 'energy saving', 'turbo mode'] },
    { action: 'query', patterns: ['what is', 'whats the', 'what are', 'how many', 'how much', 'check', 'is the', 'are the', 'tell me', 'show me', 'status of', 'status', 'is my', 'am i'] },
    { action: 'schedule', patterns: ['schedule', 'set timer', 'timer for', 'remind me', 'in 10 minutes', 'in 5 minutes', 'in 15 minutes', 'in 30 minutes', 'at 10 pm', 'at 10 am', 'every day', 'every morning'] },
    { action: 'all', patterns: ['all lights', 'all devices', 'everything in', 'turn off all', 'turn on all', 'all fans', 'all ac', 'all appliances'] },
  ],

  deviceSynonyms: {
    grinder: 'Mixi',
    mixer: 'Mixi',
    mixie: 'Mixi',
    mixi: 'Mixi',
    ac: 'Air Conditioner',
    'air conditioner': 'Air Conditioner',
    'air conditioning': 'Air Conditioner',
    cooler: 'Air Conditioner',
    tv: 'Television',
    television: 'Television',
    telly: 'Television',
    bulb: 'Light',
    lamp: 'Light',
    lights: 'Light',
    'ceiling fan': 'Ceiling Fan',
    fans: 'Ceiling Fan',
    fridge: 'Refrigerator',
    refrigerator: 'Refrigerator',
    freezer: 'Refrigerator',
    'washing machine': 'Washer',
    washer: 'Washer',
    exhaust: 'Exhaust Fan',
    'exhaust fan': 'Exhaust Fan',
    heater: 'Heater',
    'water heater': 'Heater',
    geyser: 'Heater',
    router: 'Wi-Fi Router',
    wifi: 'Wi-Fi Router',
    modem: 'Wi-Fi Router',
    speaker: 'Smart Speaker',
    'smart speaker': 'Smart Speaker',
    sensor: 'Motion Sensor',
    'motion sensor': 'Motion Sensor',
    camera: 'Security Camera',
    'security camera': 'Security Camera',
    cctv: 'Security Camera',
    doorbell: 'Doorbell',
    'smart doorbell': 'Doorbell',
    vacuum: 'Vacuum Cleaner',
    'vacuum cleaner': 'Vacuum Cleaner',
    robot: 'Vacuum Cleaner',
    dryer: 'Dryer',
    'clothes dryer': 'Dryer',
    microwave: 'Microwave',
    oven: 'Microwave',
    kettle: 'Electric Kettle',
    toaster: 'Toaster',
  },

  roomAliases: {
    kitchen: 'Kitchen',
    dinning: 'Dining Room',
    'dining room': 'Dining Room',
    'dinning room': 'Dining Room',
    living: 'Living Room',
    'living room': 'Living Room',
    'living area': 'Living Room',
    lounge: 'Living Room',
    hall: 'Living Room',
    bedroom: 'Bedroom',
    'bed room': 'Bedroom',
    master: 'Master Bedroom',
    'master bedroom': 'Master Bedroom',
    'master bed room': 'Master Bedroom',
    guest: 'Guest Room',
    'guest room': 'Guest Room',
    bathroom: 'Bathroom',
    'wash room': 'Bathroom',
    study: 'Study Room',
    'study room': 'Study Room',
    office: 'Home Office',
    'home office': 'Home Office',
    garage: 'Garage',
    terrace: 'Terrace',
    balcony: 'Balcony',
    garden: 'Garden',
    yard: 'Garden',
    backyard: 'Garden',
    'pooja room': 'Pooja Room',
    store: 'Store Room',
    'store room': 'Store Room',
    utility: 'Utility Room',
    'utility room': 'Utility Room',
    kids: 'Kids Room',
    'kids room': 'Kids Room',
    children: 'Kids Room',
  },
};

export default voiceConfig;
